/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9 at Wed Feb  7 23:11:10 2018. */

#ifndef PB_MSG_PB_H_INCLUDED
#define PB_MSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MsgConnectReq {
    char dummy_field;
/* @@protoc_insertion_point(struct:MsgConnectReq) */
} MsgConnectReq;

typedef struct _MsgConnectRsp {
    char dummy_field;
/* @@protoc_insertion_point(struct:MsgConnectRsp) */
} MsgConnectRsp;

typedef struct _MsgPrintRsp {
    char dummy_field;
/* @@protoc_insertion_point(struct:MsgPrintRsp) */
} MsgPrintRsp;

typedef struct _MsgPrintReq {
    char text[20];
/* @@protoc_insertion_point(struct:MsgPrintReq) */
} MsgPrintReq;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MsgConnectReq_init_default               {0}
#define MsgConnectRsp_init_default               {0}
#define MsgPrintReq_init_default                 {""}
#define MsgPrintRsp_init_default                 {0}
#define MsgConnectReq_init_zero                  {0}
#define MsgConnectRsp_init_zero                  {0}
#define MsgPrintReq_init_zero                    {""}
#define MsgPrintRsp_init_zero                    {0}

/* Field tags (for use in manual encoding/decoding) */
#define MsgPrintReq_text_tag                     1

/* Struct field encoding specification for nanopb */
extern const pb_field_t MsgConnectReq_fields[1];
extern const pb_field_t MsgConnectRsp_fields[1];
extern const pb_field_t MsgPrintReq_fields[2];
extern const pb_field_t MsgPrintRsp_fields[1];

/* Maximum encoded size of messages (where known) */
#define MsgConnectReq_size                       0
#define MsgConnectRsp_size                       0
#define MsgPrintReq_size                         22
#define MsgPrintRsp_size                         0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
