/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Wed Feb  7 23:11:10 2018. */

#include "msg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MsgConnectReq_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t MsgConnectRsp_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t MsgPrintReq_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, MsgPrintReq, text, text, 0),
    PB_LAST_FIELD
};

const pb_field_t MsgPrintRsp_fields[1] = {
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
